### ISSUE TITLE
Python 3.6.5 invalidSyntax

### ISSUE THREAD

**Issue by demogorgi** [yarongon/python_spt#1]
The line
`direct_reachable_nodes = filter(lambda (n1, n2, data): n2 in s2, direct_reachable_nodes)`
produces a SyntaxError: invalid syntax

Are the round brackets around the arguments correct?

Also
`smallest_weight_edge = min(direct_reachable_nodes, key=lambda (n1, n2, data): data)`
results in a syntax error.

**Comment by yarongon** [comment]
Fixed.
Thanks!
