### ISSUE TITLE
Link dead

### ISSUE THREAD

**Issue by demogorgi** [yarongon/python_spt#2]
The link http://www.me.utexas.edu/~jensen/exercises/mst_spt/spt_demo/spt1.html does not work

**Comment by yarongon** [comment]
Also, [internet archive](https://web.archive.org/web/*/http://www.me.utexas.edu/~jensen/exercises/mst_spt/spt_demo/spt1.html) doesn't work... I'll look for another description of the algorithm.

**Comment by yarongon** [comment]
Internet archive is back! here's the [link](https://web.archive.org/web/20200124171216/http://www.me.utexas.edu/~jensen/exercises/mst_spt/spt_demo/spt1.html).
